### ISSUE TITLE
ページフロー図を作る

### ISSUE THREAD

**Issue by cocuh** [kiritantan/ShishoSan#13]
登録画面や一覧画面などのページ(view)のフローを作ってください。

**Comment by kiritantan** [comment]
![shishosan_flow](https://cloud.githubusercontent.com/assets/7589600/7903827/28aab420-0823-11e5-942e-4b738ad9e956.png)

α版では上記フローを予定しているのですが、どうでしょうか？

**Comment by cocuh** [comment]
@kiritantan  小説閲覧とは。イメージ図でもいいから書いてくれるとうれしい

**Comment by cocuh** [comment]
@kiritantan それと、小説登録したらトップに飛ぶの？その小説の詳細情報とかじゃなくていいの？

**Comment by kiritantan** [comment]
@cocuh
小説を連続して登録(複数登録したい)場合を考えて「小説を登録→詳細情報→再び小説登録 || トップ」のような遷移が良いと考えたのですがどうでしょうか？

![untitled](https://cloud.githubusercontent.com/assets/7589600/7904618/cd5037ec-083d-11e5-9043-eb590ad4ed43.png)

小説を同時に複数登録できるようにするならば下図のような遷移が良いかと思いました。

![untitled 2](https://cloud.githubusercontent.com/assets/7589600/7904692/0d4b601c-0841-11e5-9d36-038b36388ef5.png)

詳細情報として「小説のタイトル・何話（まで読んでいるか）」と別に、小説の作者・掲載されているサイト名を表示したいのですが、必要ない情報・追加した方が良いかもしれない情報ってありますか？

**Comment by cocuh** [comment]
詳細情報と閲覧情報の違いがわからない。現時点でサポートするのは管理機能であって閲覧機能はないのでは？

複数登録を現時点で考えるのはあまりよくないとおもう。
実際に作ってみないとわからないだろうし、ロジックが複数可可能でないこともある。
少なくとも私は登録後は小説の詳細画面でコメントとかフラグを確認できることのほうが複数登録するより操作性が高いと思う。
複数登録させたいのであれば、csvとかtableなど別の手段があるしその方フローを変えるよりよっぽど効果的だと思うんだけど。

> 必要ない情報・追加したほうが良い情報

現時点の俺最強案を出してくれないと甲乙つけがたいんやけど…

**Comment by kiritantan** [comment]
> 現時点でサポートするのは管理機能であって閲覧機能はないのでは？

管理機能だけ実装して、閲覧は実際に小説のurlが掲載されているサイトに飛ばすという感じになりますかね…?

> 現時点の俺最強案

小説の最低限の情報ということで「小説のタイトル・作者・掲載されているサイト」を考えています

> 詳細情報と閲覧情報の違いがわからない

詳細情報は「小説のタイトル・作者・掲載されているサイト」
閲覧情報は「タイトル・作者・本文」
と考えています。

**Comment by cocuh** [comment]
@kiritantan まだいいたいことはあるけれど、とりあえずそれでview書いてみてください。  
採用するフローをwikiに乗せてcloseでよいです。

**Comment by kiritantan** [comment]
@cocuh 了解です！
